# docker-compose.yml
version: '3.8'
services:
  bola-advanced-app:
    build: .
    container_name: bola-advanced-app
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
